### ISSUE TITLE
Cog should re-authenticate client if API key expires

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-pardot#12]
### Repro Steps
1. Create a test scenario like the one below

```yml
scenario: 62 Minute Pardot Test

steps:
- step: When I create a Pardot Prospect
  data:
    prospect:
      email: too-long@example.com
- waitFor: 3720
  step: Then the email field on Pardot Prospect too-long@example.com should be too-long@example.com
- step: Delete the too-long@example.com Pardot Prospect
```

2. Run the scenario

**Expected**: The scenario to run (for about 62 minutes) and pass.

**Actual**: The check step results in an error with the following message:
```
There was a problem creating the Prospect: Error: Invalid API key or user key
```

^ Note also the wrong error message, referring to the creation of a prospect.
