### ISSUE TITLE
Logic of greater than and less than is swapped

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-pardot#21]
Repro Steps:
1. Run the yml file.
```yml
scenario: Pardot API Test
description: This test the creation and validation of field in Pardot.

steps:
- step: create a pardot prospect
  data:
    prospect:
        first_name: Rosan
        last_name: Angeles
        email: pardotapiwop@thisisjust.atomatest.com
        company: HS Corp
        is_do_not_email: 1
- step: Validate that the email field on Pardot prospect pardotapiros@thisisjust.atomatest.com should be pardotapiros@thisisjust.atomatest.com
- step: Validate that the first_name field on Pardot prospect pardotapiros@thisisjust.atomatest.com should not be Roan
- step: Validate that the last_name field on Pardot prospect pardotapiros@thisisjust.atomatest.com should contain Angel
- step: Validate that the is_do_not_email field on Pardot prospect pardotapiros@thisisjust.atomatest.com should be greater than 0
- step: Delete the pardotapiros@thisisjust.atomatest.com Pardot prospect.
```

![image](https://user-images.githubusercontent.com/54615569/70121130-f04b3980-16a8-11ea-9c5c-db68c631c04f.png)
