### ISSUE TITLE
New Step: Check list membership

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-pardot#34]
## What / Why
As a Crank user, I should be able to check that a Pardot Prospect is a member of a list and whether or not the Prospect is opted out.

**Proposed Step Name**: Check Pardot List Membership
**Proposed Step Expression**: `the pardot prospect (?<email>.+) should be (?<optInOut>(opted in to|opted out of)) list (?<listId>.+)`

**Proposed Step Fields**:
- `email` (type `EMAIL`), the email address of the prospect
- `optInOut` (type `STRING`), one of `opted in to` or `opted out of`
- `listId` (type `NUMERIC`), the ID of the pardot list

## Proposed Resolution
- Load the prospect for the given email address and note its ID.
- [Query list memberships](http://developer.pardot.com/kb/api-version-4/list-memberships/#supported-search-criteria) for
  - 1. The given `listId`
  - 2. With `updated_after` set to `last_7_days` (since it's not possible to filter the query by the prospect email address)
- Filter the resulting list memberships and only return the one associated with the previously noted prospect ID

**Outcomes**
- When `optInOut` is set to `opted in to`
  - If no [ListMembership](http://developer.pardot.com/kb/object-field-references/#list-membership) is found, the step should fail: `Prospect %s is not a member of list %d.`
  - The step should pass if a ListMembership is found and `opted_out` field is false-y (e.g. not set or `false` or `0`)
  - If the `opted_out` property is truth-y, the step should fail: `Expected prospect %s to be opted in to list %d, but the prospect is opted out.`
- When `optInOut` is set to `opted out of`
  - If no ListMembership is found, the step should result in an error: `Prospect %s is not a member of list %d.`
  - The step should pass if a ListMembership is found and `opted_out` is truth-y (e.g. set to `1`).
  - If the `opted_out` property is false-y, the step should fail: `Expected prospect %s to be opted out of list %d, but the prospect is opted in.`
- In any case, if there is no prospect for the given email address, the step should result in an error: `No prospect found for email %s`

**Structured Data**
In any situations where a single [ListMembership](http://developer.pardot.com/kb/object-field-references/#list-membership) object was found, it should be returned as a KeyValue record.

**Comment by iamEAP** [comment]
Some sample UAT scenarios:

```yml
scenario: Static List Membership
description: Proves list membership check works for static lists

tokens:
  test.email: static-pi@example.com

steps:
- step: Given I navigate to http://go.pardot.com/l/811013/2019-10-16/3mxyx
- step: And I fill out .qat-email-address input with {{test.email}}
- step: And I submit the form by clicking input[type="submit"]
- step: When I navigate to http://go.pardot.com/emailPreference/e/epc/811013/73l8a8WE9ADUxfXqsuccHNdSbUtyYnSPsF84xjhVW0g/411
- step: And I fill out input#list_20395 with 1
- step: And I submit the form by clicking input[type="submit"]
- step: Then the {{test.email}} Pardot Prospect should be opted in to list 20395
- step: Finally, delete the {{test.email}} Pardot Prospect
```

```yml
scenario: Dynamic List Membership
description: Proves list membership check works for dynamic lists

tokens:
  test.email: dynamic@example.com

steps:
- step: Given I create a Pardot Prospect
  data:
    prospect:
      email: '{{test.email}}'
      utm_campaign: DynamicSubscribe
- step: Then the {{test.email}} Pardot Prospect should be opted in to list 20397
- step: Finally, delete the {{test.email}} Pardot Prospect
```
